### ISSUE TITLE
建議用 block quotation 語法標註訊息內容

### ISSUE THREAD

**Issue by andy0130tw** [kiko555/MeshtasticMQTT2Telegram#1]
目前是用程式碼區塊的方式來區分訊息來源和內容： ````msg_content = f"```\n{text_payload}```"````

但我查了一下 Telegram Bot API [支援的語法格式](https://core.telegram.org/bots/api#formatting-options) 發現似乎可以用「引文區塊」來表示，就不用侷限於等寬字體顯示，方便閱讀。請見在 Android 和 iOS 上的顯示方式比較：

<img alt=Android src=https://github.com/kiko555/MeshtasticMQTT2Telegram/assets/5269414/7ef9b3d0-03a3-42c1-9022-13a1ff444ff1 width=300>

<img alt=iOS src=https://github.com/kiko555/MeshtasticMQTT2Telegram/assets/5269414/8a1ac5a2-cda0-482c-bb30-0604790b6cdd width=300>

不過字串處理會變得比較麻煩，需要將訊息斷行之後在行首插入 `>` 符號，最後用 `**` 或 `\r` 結尾。提供參考程式碼如下：

```python
>>> s = 'aaa\nbbb\nccc'
>>> s.split('\n')
['aaa', 'bbb', 'ccc']
>>> '>' + '\n>'.join(s.split('\n')) + '\r'
'>aaa\n>bbb\n>ccc\r'
```

**Comment by kiko555** [comment]
您的建議很棒，原本我也是要採用 > 的，但當時一直不成功，才改用程式碼區塊，不過剛好借著您的這個建議，我又好好的檢查一下，終於解決問題了，感謝您的建議。
